volumes:
  caddy_data:
  caddy_config:

services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
      target: build-development
    image: app:frankenphp
    restart: unless-stopped
    tty: true
    volumes:
      - ./build/Caddyfile:/etc/caddy/Caddyfile:ro
      - ./src:/app
      - caddy_data:/data
      - caddy_config:/config
    ports:
      - 80:80
      - 443:443
      - 443:443/udp
    healthcheck:
      test: ["CMD", "wget", "--spider", "https://website.localhost/healthcheck"]
      interval: 10s
      timeout: 1s
      retries: 3
