services:
    app1:
        extends:
            file: docker-compose.yml
            service: custom-frankenphp
        build:
            context: .
            dockerfile: Dockerfile
            target: build-production
        image: dockerized-php-frankenphp:prod
